### PR TITLE
[Fix]: #1 Add vacation message for empty playlists in PlaylistList.js 

### LINKED ISSUE #1: Display appropriate message when there is no playlist added
Initially, when a user signs up, there is no playlist, or maybe the user deletes all the playlists, Display appropriate messages aligning with the UI. 

For eg:
"No playlist added, Add it now."

Screenshot 2024-03-13 at 10 16 36 PM

### PR DESCRIPTION
**Pull request by PriyanshuPz**
**Description**

- Add vacation message for empty playlists in PlaylistList.js 

**Related issue(s)**
- Fixed #1

### CODE REVIEW

**Comment by janvi01** [comment]
@priyanshuverma-dev Thanks for the PR, it works fine but when there is a playlist there, it still shows this message initially when the page loads for I guess like 1 second, please crosscheck and fix it.

**Review by janvi01 — CHANGES_REQUESTED** [review]
@priyanshuverma-dev Thanks for the PR, it works fine but when there is a playlist there, it still shows this message initially when the page loads for I guess like 1 second, please crosscheck and fix it.

**Comment by PriyanshuPz** [comment]
Fixed 1 second delay and I don't have environment vars so I can't cross check. @janvi01

**Review by janvi01 — CHANGES_REQUESTED** [review]
Uploading Screen Recording 2024-04-14 at 11.45.17 AM.mov…

Adding this for reference.

**Comment by janvi01** [comment]
https://github.com/janvi01/TuList/assets/34344234/1d7908a4-eb84-48a9-bdbb-f555dca4b581

**Review by janvi01 — APPROVED** [review]

**Pull request merged**
